Feat: add "from" and "to" query params to GET /games
tf2pickup-org/server pull request #2839
Opened 2024-07-01 01:51 UTC by maxijabase

2024-07-01 07:54 UTC, garrappachc requested changes

2024-07-01 07:54 UTC, garrappachc commented on src/shared/pipes/parse-date.pipe.ts
> +    const date = moment(value, 'YYYY-MM-DD', true);
Use `date-fns` instead of `moment`

2024-07-01 07:54 UTC, garrappachc commented
Nice one, thanks!

2024-07-01 13:26 UTC, maxijabase commented
The functionality I intended is to check against the `ended` date, since that would mean a game actually finished and can count as "valid"? Or since that's what I want to do, is it best to check for the `created` date and pass `state=ended`?

2024-07-02 08:11 UTC, garrappachc commented
> The functionality I intended is to check against the `ended` date, since that would mean a game actually finished and can count as "valid"? Or since that's what I want to do, is it best to check for the `created` date and pass `state=ended`?

`game.state` will be either `ended` or `interrupted`, but the `ended` event will be always present for ended games. I think I'd be better to compare the `created.at` instead of `ended`, since the user can also pass the `state` filter to the query and achieve the desired result, e.g.:
`/games?from=2023-01-01&to=2024-01-01&state=ended,interrupted`

> Also, is it OK the way `limit` is currently being handled with the introduction of this filter? Is it intuitive to make the player guess the amount of games that will be within the specified timestamp, or make him pass `limit=0` to bring all results?

The `limit` param is always present; the number of results is available in the `itemCount` field in the response.

2024-07-02 15:48 UTC, garrappachc approved these changes

2024-07-02 15:58 UTC, merged